# Quick CI script
stages:
  - code
  - build
  - test
flake8:
  stage: code
  allow_failure: true
  needs: []
  before_script:
    - apt update -qq
    - apt install -y python3 python3-pip -qq
    - pip3 install flake8
  script:
    - flake8 --max-line-length 512 *.py
py_compile:
  stage: build
  needs: []
  before_script:
    - apt update -qq
    - apt install -y python3 -qq
  script:
    - python3 -m py_compile *.py
test_parser:
  stage: test
  needs: []
  before_script:
    - apt update -qq
    - apt install -y python3 python3-mysql.connector python3-pip -qq
    - pip3 install bs4
    - echo "" > tests/empty.html
  script:
    - python3 kwparser.py test
